name: test
on: [ pull_request ]
jobs:
  test:
    name: test
    runs-on: ubuntu-latest

    steps:
      - name: Initialize
        uses: actions/checkout@master

      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.6.0
        with:
          java-version: 8
          maven-version: 3.8.7

      - run: mvn test
